hot_wallets.rb: process with pid 5719 started.
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:97:in `call': MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error. (Redis::CommandError)
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:691:in `block in setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:690:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:17:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `block in setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.0.2/lib/active_support/cache.rb:519:in `instrument'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /home/deploy/peatio/current/app/models/currency.rb:33:in `refresh_balance'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:18:in `each'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
hot_wallets.rb: process with pid 2394 started.
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:97:in `call': MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error. (Redis::CommandError)
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:691:in `block in setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:690:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:17:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `block in setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.0.2/lib/active_support/cache.rb:519:in `instrument'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /home/deploy/peatio/current/app/models/currency.rb:33:in `refresh_balance'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:18:in `each'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
hot_wallets.rb: process with pid 2350 started.
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:222:in `rescue in io': Connection timed out (Redis::TimeoutError)
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:691:in `block in setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:690:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:17:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `block in setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `setex'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.0.2/lib/active_support/cache.rb:519:in `instrument'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /home/deploy/peatio/current/app/models/currency.rb:33:in `refresh_balance'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:18:in `each'
	from /home/deploy/peatio/current/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
