# Logfile created on 2014-06-30 16:37:28 by logger.rb/44203
I, [2014-06-30T16:37:29.466531 #5686]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-06-30T16:37:29.466982 #5686] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-06-30T16:37:29.482069 #5686]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-06-30T16:37:29.498609 #5686] ERROR -- : stream closed (IOError)

E, [2014-06-30T16:37:29.499487 #5686] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-06-30T16:37:29.512147 #5686] ERROR -- : stack level too deep (SystemStackError)

E, [2014-06-30T16:37:29.513741 #5686] ERROR -- : exception reentered (fatal)

E, [2014-06-30T16:37:29.577759 #5686] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-06-30T16:37:29.798632 #5686] ERROR -- : No such file or directory @ rb_sysopen - /home/deploy/peatio/current/log/k.rb.log (Errno::ENOENT)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/logger.rb:318:in `new'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2014-06-30T16:37:29.799266 #5686] ERROR -- : undefined method `created_at' for nil:NilClass (NoMethodError)
/home/deploy/peatio/current/lib/daemons/k.rb:31:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T16:37:29.830787 #5686] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T16:37:29.831646 #5686] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T16:37:29.844659 #5686] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-06-30T18:33:14.756798 #2379]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-06-30T18:33:14.769633 #2379] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-06-30T18:33:14.796775 #2379]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-06-30T18:33:14.840608 #2379] ERROR -- : stream closed (IOError)

E, [2014-06-30T18:33:14.841540 #2379] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-06-30T18:33:14.846479 #2379] ERROR -- : stack level too deep (SystemStackError)

E, [2014-06-30T18:33:14.848095 #2379] ERROR -- : exception reentered (fatal)

E, [2014-06-30T18:33:14.965205 #2379] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-06-30T18:33:15.678229 #2379] ERROR -- : undefined method `created_at' for nil:NilClass (NoMethodError)
/home/deploy/peatio/current/lib/daemons/k.rb:31:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T18:33:15.700888 #2379] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T18:33:15.707131 #2379] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T18:33:15.708093 #2379] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-06-30T19:22:21.768023 #2331]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-06-30T19:22:21.819886 #2331] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-06-30T19:22:21.872761 #2331]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-06-30T19:22:21.888893 #2331] ERROR -- : stream closed (IOError)

E, [2014-06-30T19:22:21.907375 #2331] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-06-30T19:22:21.912038 #2331] ERROR -- : stack level too deep (SystemStackError)

E, [2014-06-30T19:22:21.919571 #2331] ERROR -- : exception reentered (fatal)

E, [2014-06-30T19:22:23.066663 #2331] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-06-30T19:22:23.577309 #2331] ERROR -- : undefined method `created_at' for nil:NilClass (NoMethodError)
/home/deploy/peatio/current/lib/daemons/k.rb:31:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T19:22:23.606786 #2331] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T19:22:23.617018 #2331] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-06-30T19:22:23.618157 #2331] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/deploy/peatio/current/lib/daemons/k.rb:26:in `next_ts'
/home/deploy/peatio/current/lib/daemons/k.rb:84:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `each'
/home/deploy/peatio/current/lib/daemons/k.rb:83:in `<top (required)>'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
